language: node_js
node_js:
- node
sudo: required
dist: trusty
branches:
  only:
  - master
before_install:
# 安装编译依赖
- sudo pip install Pygments
- sudo pip install pygments-lexer-solidity
install:
- mkdir work
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  -O $PWD/work/hugo.deb
- sudo dpkg -i $PWD/work/hugo.deb
- npm install
before_deploy:
- grunt build
# 解密
- openssl aes-256-cbc -K $encrypted_98e3fd917d2e_key -iv $encrypted_98e3fd917d2e_iv -in deploy_rsa.enc -out deploy_rsa -d
# 将私钥加入环境
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa  

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: "$GH_TOKEN"  
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/$SOURCE_DIR $DEPLOY_SSH_USER@$DEPLOY_HOST:./ehtereumhelp/
  on:
    branch: master
env:
  global:
  - REPO="github.com/mochain/ethereumhelp.git"
  - USER="ysqi"
  - EMAIL="devysq@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="gh-pages"
